services:
  # mongo:
  #   image: mongodb/mongodb-community-server:latest
  #   expose:
  #     - 27017
  api:
    build:
      context: .
      dockerfile: api.dockerfile
    ports:
      - 8081:8081
    env_file:
      - docker.env
    networks:
      - postgres
  ui:
    build:
      context: .
      dockerfile: ui.dockerfile
    ports:
      - 8877:8877
    env_file:
      - docker.env

  postgres:
    image: postgres:16-alpine
    env_file:
      - docker.env
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bookworm_user -d bookworm_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - postgres

volumes:
  pg_data:

networks:
  postgres:
    driver: bridge
