services:
  api:
    build:
      context: .
      dockerfile: api.dockerfile
    ports:
      - 8081:8081
    env_file:
      - docker.env
    networks:
      - postgres
      - tg_to_api
  tg:
    build:
      context: .
      dockerfile: tg.dockerfile
    env_file:
      - docker.env
      - .tgbot_token.env
    environment:
      - API_URI_FOR_UI=http://api:8081
    networks:
      - tg_to_api
  ui:
    build:
      context: .
      dockerfile: ui.dockerfile
    ports:
      - 8877:8877
    env_file:
      - docker.env

  postgres:
    image: postgres:16-alpine
    env_file:
      - docker.env
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bookworm_user -d bookworm_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - postgres

volumes:
  pg_data:

networks:
  postgres:
    driver: bridge
  tg_to_api:
    driver: bridge
