services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: bookworm_user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: bookworm_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bookworm_user -d bookworm_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - postgres

  # pgadmin:
  #   container_name: pgadmin_container
  #   image: dpage/pgadmin4:7.2
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "bookworm_user@pupu.com"
  #     PGADMIN_DEFAULT_PASSWORD: "123"
  #     PGADMIN_CONFIG_SERVER_MODE: "False"
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
  #   ports:
  #     - "5050:80"
  #   restart: unless-stopped
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.5'
  #         memory: 1G
  #   networks:
  #     - postgres

volumes:
  pg_data:
  
#   pgadmin-data:

networks:
  postgres:
    driver: bridge